In [12]:
import os
import torch
import random
import numpy as np
from loguru import logger
from torch.utils.data import DataLoader
from torch import nn

from pose.dataset import pose_dataset
from pose.utils import (
    collate_fn,
    geodesic_distance,
    relative_pose_error,
    relative_pose_error_np,
    recall_object
)
from pose.model import Mkpts_Reg_Model
from pose.animator import Animator


if os.name == 'nt':
    LM_dataset_path = 'd:/git_project/POPE/data/LM_dataset/'
    LM_dataset_json_path = 'd:/git_project/POPE/data/pairs/LINEMOD-test.json'
    LM_dataset_points_path = 'd:/git_project/POPE/data/LM_dataset-points/'

    onepose_path = 'e:/datasets/OnePose/test_data/'
    onepose_json_path = 'd:/git_project/POPE/data/pairs/Onepose-test.json'
    onepose_points_path = 'd:/git_project/POPE/data/onepose-points/'

    oneposeplusplus_path = 'e:/datasets/OnePose++/lowtexture_test_data/'
    oneposeplusplus_json_path = 'd:/git_project/POPE/data/pairs/OneposePlusPlus-test.json'
    oneposeplusplus_points_path = 'd:/git_project/POPE/data/oneposeplusplus-points/'
elif os.name == 'posix':
    LM_dataset_path = 'data/LM_dataset/'
    LM_dataset_json_path = 'data/pairs/LINEMOD-test.json'
    LM_dataset_points_path = 'data/LM_dataset-points/'

    onepose_path = 'data/onepose/'
    onepose_json_path = 'data/pairs/Onepose-test.json'
    onepose_points_path = 'data/onepose-points/'

    oneposeplusplus_path = 'data/oneposeplusplus/'
    oneposeplusplus_json_path = 'data/pairs/OneposePlusPlus-test.json'
    oneposeplusplus_points_path = 'data/oneposeplusplus-points/'

paths = [
    ('linemod', LM_dataset_path, LM_dataset_json_path, LM_dataset_points_path),
    # ('onepose', onepose_path, onepose_json_path, onepose_points_path),
    # ('oneposeplusplus', oneposeplusplus_path, oneposeplusplus_json_path, oneposeplusplus_points_path),
]

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

dataset = pose_dataset(paths)
mkpts_max_len, mkpts_sum_len = dataset.get_mkpts_info()

 62%|██████▏   | 8/13 [00:10<00:05,  1.19s/it]

d:/git_project/POPE/data/LM_dataset-points/0811-lm11-others\mkpts0\844.png-736.png.txt does not exist
d:/git_project/POPE/data/LM_dataset-points/0811-lm11-others\mkpts0\142.png-144.png.txt does not exist
d:/git_project/POPE/data/LM_dataset-points/0811-lm11-others\mkpts0\860.png-873.png.txt does not exist
d:/git_project/POPE/data/LM_dataset-points/0811-lm11-others\mkpts0\142.png-111.png.txt does not exist
d:/git_project/POPE/data/LM_dataset-points/0811-lm11-others\mkpts0\841.png-485.png.txt does not exist


 69%|██████▉   | 9/13 [00:11<00:04,  1.21s/it]

d:/git_project/POPE/data/LM_dataset-points/0812-lm12-others\mkpts0\582.png-581.png.txt does not exist


100%|██████████| 13/13 [00:15<00:00,  1.23s/it]


In [13]:
random.seed(20231223)
torch.manual_seed(20231223)
torch.cuda.manual_seed(20231223)

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [train_size, test_size])

In [14]:
num_sample = 500
train_dataloader = DataLoader(train_dataset, batch_size=8, shuffle=True, drop_last=True, collate_fn=collate_fn(num_sample))
test_dataloader = DataLoader(test_dataset, batch_size=8, shuffle=True, drop_last=True, collate_fn=collate_fn(num_sample))

In [15]:
net = torch.load('./weights/linemod-relative_r-gt_t-6d-500-2024-01-08-13-02-42-1.6629.pth').to(device)

net.eval()

Mkpts_Reg_Model(
  (embedding): Embedding()
  (transformerlayer): TransformerEncoderLayer(
    (self_attn): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=76, out_features=76, bias=True)
    )
    (linear1): Linear(in_features=76, out_features=2048, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (linear2): Linear(in_features=2048, out_features=76, bias=True)
    (norm1): LayerNorm((76,), eps=1e-05, elementwise_affine=True)
    (norm2): LayerNorm((76,), eps=1e-05, elementwise_affine=True)
    (dropout1): Dropout(p=0.1, inplace=False)
    (dropout2): Dropout(p=0.1, inplace=False)
  )
  (transformer): TransformerEncoder(
    (layers): ModuleList(
      (0-3): 4 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=76, out_features=76, bias=True)
        )
        (linear1): Linear(in_features=76, out_features=2048, bias=True)
        (dropout): Dropout(p=0.1, inp

In [16]:
id2name_dict = {
    1: "ape",
    2: "benchvise",
    4: "camera",
    5: "can",
    6: "cat",
    8: "driller",
    9: "duck",
    10: "eggbox",
    11: "glue",
    12: "holepuncher",
    13: "iron",
    14: "lamp",
    15: "phone",
}

In [17]:
# linemod
ape_data = []
benchvise_data = []
camera_data = []
can_data = []
cat_data = []
driller_data = []
duck_data = []
eggbox_data = []
glue_data = []
holepuncher_data = []
iron_data = []
lamp_data = []
phone_data = []
# onepose
aptamil_data = []
jzhg_data = []
minipuff_data = []
hlyormosiapie_data = []
brownhouse_data = []
oreo_data = []
mfmilkcake_data = []
diycookies_data = []
taipingcookies_data = []
tee_data = []
# onepose++
toyrobot_data = []
yellowduck_data = []
sheep_data = []
fakebanana_data = []
teabox_data = []
orange_data = []
greenteapot_data = []
lecreusetcup_data = []
insta_data = []

all_data = {
    # linemod
    'ape_data': ape_data,
    'benchvise_data': benchvise_data,
    'camera_data': camera_data,
    'can_data': can_data,
    'cat_data': cat_data,
    'driller_data': driller_data,
    'duck_data': duck_data,
    'eggbox_data': eggbox_data,
    'glue_data': glue_data,
    'holepuncher_data': holepuncher_data,
    'iron_data': iron_data,
    'lamp_data': lamp_data,
    'phone_data': phone_data,
    # onepose
    'aptamil_data': aptamil_data,
    'jzhg_data': jzhg_data,
    'minipuff_data': minipuff_data,
    'hlyormosiapie_data': hlyormosiapie_data,
    'brownhouse_data': brownhouse_data,
    'oreo_data': oreo_data,
    'mfmilkcake_data': mfmilkcake_data,
    'diycookies_data': diycookies_data,
    'taipingcookies_data': taipingcookies_data,
    'tee_data': tee_data,
    # onepose++
    'toyrobot_data': toyrobot_data,
    'yellowduck_data': yellowduck_data,
    'sheep_data': sheep_data,
    'fakebanana_data': fakebanana_data,
    'teabox_data': teabox_data,
    'orange_data': orange_data,
    'greenteapot_data': greenteapot_data,
    'lecreusetcup_data': lecreusetcup_data,
    'insta_data': insta_data,
}

In [18]:
linemod_type = ['ape_data', 'benchvise_data', 'camera_data', 'can_data', 'cat_data', 'driller_data', 'duck_data', 'eggbox_data', 'glue_data', 'holepuncher_data', 'iron_data', 'lamp_data', 'phone_data']
onepose_type = ['aptamil_data', 'jzhg_data', 'minipuff_data', 'hlyormosiapie_data', 'brownhouse_data', 'oreo_data', 'mfmilkcake_data', 'diycookies_data', 'taipingcookies_data', 'tee_data']
oneposeplusplus_type = ['toyrobot_data', 'yellowduck_data', 'sheep_data', 'fakebanana_data', 'teabox_data', 'orange_data', 'greenteapot_data', 'lecreusetcup_data', 'insta_data']

In [19]:
for i, batch in enumerate(test_dataloader):
    for data in batch:
        if 'lm' in data['name']:
            all_data[f"{id2name_dict[int(data['name'][2:])]}_data"].append(data)
        else:
            all_data[f"{data['name']}_data"].append(data)

empty_keys = []
for key in all_data.keys():
    if len(all_data[key]) == 0:
        empty_keys.append(key)

for key in empty_keys:
    all_data.pop(key)

for key in all_data.keys():
    print(key, len(all_data[key]))

print('len(all_data):', len(all_data))

ape_data 102
benchvise_data 71
camera_data 125
can_data 86
cat_data 100
driller_data 98
duck_data 95
eggbox_data 50
glue_data 106
holepuncher_data 101
iron_data 45
lamp_data 84
phone_data 89
len(all_data) 13


In [9]:
res_table = []

model_type = 'relative_r-gt_t'

for key in all_data.keys():
    if key in linemod_type:
        logger.info(f"LINEMOD: {key}")
    elif key in onepose_type:
        logger.info(f"ONEPOSE: {key}")
    elif key in oneposeplusplus_type:
        logger.info(f"ONEPOSE++: {key}")
    metrics = dict()
    metrics.update({'R_errs':[], 't_errs':[], 'inliers':[], "identifiers":[]})
    recall_image, all_image = 0, 0
    for item in all_data[key]:
        all_image += 1
        K0 = item['K0']
        K1 = item['K1']
        pose0 = item['pose0']
        pose1 = item['pose1']
        pre_bbox = item['pre_bbox']
        gt_bbox = item['gt_bbox']
        mkpts0 = item['mkpts0']
        mkpts1 = item['mkpts1']
        pre_K = item['pre_K']
        name = item['name']
        pair_name = item['pair_name']
        if 'lm' in name:
            name = id2name_dict[int(name[2:])]
        if name not in key:
            print(f'name: {name}, key: {key}')
            continue

        is_recalled = recall_object(pre_bbox, gt_bbox)

        recall_image = recall_image + int(is_recalled > 0.5)

        batch_mkpts0 = torch.from_numpy(mkpts0).unsqueeze(0).float().to(device)
        batch_mkpts1 = torch.from_numpy(mkpts1).unsqueeze(0).float().to(device)
        pre_t, pre_rot = net(batch_mkpts0, batch_mkpts1)
        pre_t = pre_t.squeeze(0).detach().cpu().numpy()
        pre_rot = pre_rot.squeeze(0).detach().cpu().numpy()

        if model_type == 'gt':
            t_err, R_err = relative_pose_error_np(pose1, pre_rot, pre_t, ignore_gt_t_thr=0.0)
        elif model_type == 'relative':
            relative_pose = np.matmul(pose1, np.linalg.inv(pose0))
            t_err, R_err = relative_pose_error_np(relative_pose, pre_rot, pre_t, ignore_gt_t_thr=0.0)
        elif model_type == 'relative_r-gt_t':
            relative_pose = np.matmul(pose1, np.linalg.inv(pose0))
            gt_pose = np.zeros_like(pose1)
            gt_pose[:3, :3] = relative_pose[:3, :3]
            gt_pose[:3, 3] = pose1[:3, 3]
            t_err, R_err = relative_pose_error_np(gt_pose, pre_rot, pre_t, ignore_gt_t_thr=0.0)

        metrics['R_errs'].append(R_err)
        metrics['t_errs'].append(t_err)
        metrics['identifiers'].append(pair_name)

    print(f"Acc: {recall_image}/{all_image}")
    import pprint
    from src.utils.metrics import (
        aggregate_metrics
    )
    from loguru import logger
    val_metrics_4tb = aggregate_metrics(metrics, 5e-4)
    val_metrics_4tb["AP50"] = recall_image / all_image
    logger.info('\n' + pprint.pformat(val_metrics_4tb))
    res_table.append([f"{name}"] + list(val_metrics_4tb.values()))

2024-01-08 18:25:53.742 | INFO     | __main__:<module>:7 - LINEMOD: ape_data


pre_t:
[ 0.03325049 -0.07125819  0.84045446]
gt_t:
[-0.13250454  0.03350499  0.79338747]
relative_t:
[0.79737847 0.19489724 0.38759566]
pre_t:
[0.003309   0.07818821 0.94732827]
gt_t:
[-0.22878009 -0.03225575  0.96876669]
relative_t:
[-0.02636355  0.10462934  0.3247855 ]
pre_t:
[ 0.0655687  -0.05722878  0.90606755]
gt_t:
[-0.01247146  0.14136802  0.86857212]
relative_t:
[-0.34623108 -0.55867123  0.68684115]
pre_t:
[ 0.03417    -0.0491489   0.80214715]
gt_t:
[-0.03973154  0.1757955   1.018682  ]
relative_t:
[ 0.29300905 -0.70840105  0.62918035]
pre_t:
[-0.05172608 -0.08968486  0.95460767]
gt_t:
[ 0.05826002 -0.07230116  0.80790097]
relative_t:
[-0.09401229 -0.88879636  0.82849514]
pre_t:
[ 0.03192649 -0.01357263  0.8399208 ]
gt_t:
[ 0.18148552 -0.03191694  0.94017565]
relative_t:
[-0.20008389 -0.30509212  0.28084449]
pre_t:
[ 0.01143481 -0.05350747  0.81917137]
gt_t:
[-0.10738782 -0.02690611  0.83542573]
relative_t:
[ 0.39638788 -0.62946606  1.56345192]
pre_t:
[ 0.02719515 -0.05594535  

2024-01-08 18:25:57.093 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 102 unique items...
2024-01-08 18:25:57.095 | INFO     | __main__:<module>:71 - 
{'AP50': 0.6372549019607843,
 'R:ACC15': 0.00980392156862745,
 'R:ACC30': 0.1568627450980392,
 'R:auc@15': 0.007805654284870509,
 'R:auc@30': 0.04351889164697343,
 'R:medianErr': 66.19761793782445,
 't:ACC15': 0.9313725490196079,
 't:ACC30': 1.0,
 't:auc@15': 0.43515016702862364,
 't:auc@30': 0.7137732253403046,
 't:medianErr': 8.665881127078187}
2024-01-08 18:25:57.095 | INFO     | __main__:<module>:7 - LINEMOD: benchvise_data


pre_t:
[ 0.08460239 -0.02133844  0.8478926 ]
gt_t:
[ 0.03925488 -0.11446255  0.66365081]
relative_t:
[-0.57982678  0.03552358  0.10185835]
pre_t:
[-0.01234867 -0.02034062  0.9125377 ]
gt_t:
[0.14475785 0.0087794  1.02957964]
relative_t:
[-0.11079038 -0.28663833  0.51092958]
pre_t:
[ 0.02023221 -0.06103107  0.8650328 ]
gt_t:
[0.09863744 0.09088158 1.02459717]
relative_t:
[-0.43436263 -0.43755508  1.30257326]
pre_t:
[ 0.04092666 -0.06070082  0.8615607 ]
gt_t:
[-0.06534532  0.02682884  0.92463911]
relative_t:
[-0.30646527 -0.57397285  0.9588506 ]
pre_t:
[ 0.01832808 -0.04512085  0.8999933 ]
gt_t:
[-0.03483285 -0.04023927  0.6915099 ]
relative_t:
[-0.67884716  0.06068082  0.32926931]
pre_t:
[4.2070448e-04 2.6755624e-02 9.0189654e-01]
gt_t:
[ 0.02976879 -0.01674361  0.98377091]
relative_t:
[ 0.07870379 -0.56431284  1.39005994]
pre_t:
[-0.04633661 -0.0943611   0.8626997 ]
gt_t:
[0.03744414 0.04485041 0.78113192]
relative_t:
[-0.03558685  0.33797916  0.19675689]
pre_t:
[ 0.05029139 -0.0374708

2024-01-08 18:25:57.773 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 71 unique items...
2024-01-08 18:25:57.775 | INFO     | __main__:<module>:71 - 
{'AP50': 0.3380281690140845,
 'R:ACC15': 0.014084507042253521,
 'R:ACC30': 0.11267605633802817,
 'R:auc@15': 0.007731367806768512,
 'R:auc@30': 0.04191436602460065,
 'R:medianErr': 90.45960979109566,
 't:ACC15': 1.0,
 't:ACC30': 1.0,
 't:auc@15': 0.5747023887278764,
 't:auc@30': 0.7873511943639381,
 't:medianErr': 6.1466996162332865}
2024-01-08 18:25:57.776 | INFO     | __main__:<module>:7 - LINEMOD: camera_data


pre_t:
[0.02044801 0.01977282 0.91826254]
gt_t:
[ 0.07840455 -0.05163197  0.99283367]
relative_t:
[-0.47684027 -0.24183522  0.22234946]
pre_t:
[ 0.05063112 -0.02570436  0.923643  ]
gt_t:
[ 0.08474334 -0.00548706  0.94962937]
relative_t:
[0.93627572 0.20281916 0.40280524]
pre_t:
[ 0.0082439  -0.05999362  0.8984558 ]
gt_t:
[ 0.03083967 -0.03397091  0.98330235]
relative_t:
[-0.1253232  -0.54437875  0.49502795]
pre_t:
[-0.01552712 -0.07989734  0.8699165 ]
gt_t:
[ 0.01691561 -0.07497732  0.84563792]
relative_t:
[-0.3144612  -0.84180159  1.09171818]
Acc: 24/71
pre_t:
[ 0.02770883 -0.03196268  0.8870474 ]
gt_t:
[0.02592751 0.06116987 0.90221429]
relative_t:
[ 0.93229623 -0.29634234  0.62868978]
pre_t:
[ 0.03248379 -0.0337145   0.92517793]
gt_t:
[-0.00489133 -0.05671394  0.90421587]
relative_t:
[-0.37317841 -0.01585565 -0.07012502]
pre_t:
[ 0.0869368  -0.05079528  0.79962164]
gt_t:
[ 0.12736    -0.00661781  0.93732661]
relative_t:
[ 0.19780966 -0.80414196  0.24322859]
pre_t:
[ 0.01950517 -0.06

2024-01-08 18:25:58.959 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 125 unique items...
2024-01-08 18:25:58.961 | INFO     | __main__:<module>:71 - 
{'AP50': 0.512,
 'R:ACC15': 0.008,
 'R:ACC30': 0.12,
 'R:auc@15': 0.00486734843742984,
 'R:auc@30': 0.03600464053894994,
 'R:medianErr': 87.48273749943382,
 't:ACC15': 0.992,
 't:ACC30': 1.0,
 't:auc@15': 0.6381400462779424,
 't:auc@30': 0.8189137699043165,
 't:medianErr': 5.213680130213154}
2024-01-08 18:25:58.962 | INFO     | __main__:<module>:7 - LINEMOD: can_data


pre_t:
[-0.01773669  0.04499303  0.8875079 ]
gt_t:
[0.05084658 0.01566692 0.82005423]
relative_t:
[ 0.82550307 -0.66445425  0.78494528]
pre_t:
[ 0.01348192 -0.09404011  0.85860294]
gt_t:
[-0.05291491  0.01464367  0.76833177]
relative_t:
[-0.23326824 -0.4746121   0.34317681]
pre_t:
[0.0582702  0.02680364 0.9252747 ]
gt_t:
[ 0.08142435 -0.00924749  0.79603606]
relative_t:
[ 0.86081172 -0.02587573  0.491753  ]
pre_t:
[ 0.02355323 -0.05133684  0.9141925 ]
gt_t:
[ 0.07401904 -0.0685961   1.04546857]
relative_t:
[ 0.1186866  -0.79883796  1.13578712]
pre_t:
[ 0.05706301 -0.04781631  0.8803392 ]
gt_t:
[-0.0431985  -0.06093394  0.6715678 ]
relative_t:
[-0.23528715 -0.94137937  1.17302868]
pre_t:
[0.00383002 0.01916692 0.9213098 ]
gt_t:
[ 0.05189544 -0.00802886  0.77128071]
relative_t:
[ 0.11843407 -0.83356455  0.80244662]
pre_t:
[ 0.064619   -0.04793605  0.8185539 ]
gt_t:
[ 0.07707145 -0.03810763  1.01704693]
relative_t:
[-0.73927419 -0.68311072  1.20419108]
pre_t:
[ 0.02004064 -0.04029835  0.9

2024-01-08 18:25:59.779 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 86 unique items...
2024-01-08 18:25:59.780 | INFO     | __main__:<module>:71 - 
{'AP50': 0.6976744186046512,
 'R:ACC15': 0.023255813953488372,
 'R:ACC30': 0.1511627906976744,
 'R:auc@15': 0.012326287057043377,
 'R:auc@30': 0.04842873691330523,
 'R:medianErr': 72.19594674050137,
 't:ACC15': 0.9534883720930233,
 't:ACC30': 1.0,
 't:auc@15': 0.522535108394169,
 't:auc@30': 0.7601249667830728,
 't:medianErr': 7.344947835142073}
2024-01-08 18:25:59.781 | INFO     | __main__:<module>:7 - LINEMOD: cat_data


pre_t:
[ 0.01210033 -0.04885084  0.9170332 ]
gt_t:
[-0.03813139 -0.11775228  0.67384189]
relative_t:
[ 0.06838634 -0.75976627 -0.09921279]
pre_t:
[ 0.00865373 -0.06212731  0.8547342 ]
gt_t:
[-0.082156   -0.06232202  0.8215583 ]
relative_t:
[ 0.07898734 -0.54256906 -0.06214094]
pre_t:
[ 0.0689531  -0.05108475  0.8940113 ]
gt_t:
[ 0.07889172 -0.00975789  0.97729772]
relative_t:
[-0.79695114 -0.13347464  0.6141542 ]
pre_t:
[ 0.04641306 -0.03641353  0.80697805]
gt_t:
[ 0.10973087 -0.12072758  0.7814818 ]
relative_t:
[ 0.8053637  -0.91430649  0.99372885]
pre_t:
[ 3.517600e-02 -5.282834e-04  9.226180e-01]
gt_t:
[-0.00225306 -0.09613167  0.64972335]
relative_t:
[0.31037917 0.48628175 0.23767906]
pre_t:
[ 0.04299043 -0.0771578   0.91265804]
gt_t:
[ 0.09566108 -0.13069609  1.02697408]
relative_t:
[ 0.10810806 -1.02707239  0.63276985]
pre_t:
[0.05584899 0.00830199 0.85425794]
gt_t:
[-0.07424254 -0.01363244  0.83173585]
relative_t:
[-0.353046   -0.50456558  0.3009331 ]
pre_t:
[ 0.00664776 -0.0037

2024-01-08 18:26:00.727 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 100 unique items...
2024-01-08 18:26:00.728 | INFO     | __main__:<module>:71 - 
{'AP50': 0.63,
 'R:ACC15': 0.05,
 'R:ACC30': 0.14,
 'R:auc@15': 0.015045949512564738,
 'R:auc@30': 0.06067883320011862,
 'R:medianErr': 70.10567445994646,
 't:ACC15': 0.94,
 't:ACC30': 1.0,
 't:auc@15': 0.554526962741274,
 't:auc@30': 0.773436690249168,
 't:medianErr': 6.123681223005022}
2024-01-08 18:26:00.729 | INFO     | __main__:<module>:7 - LINEMOD: driller_data


pre_t:
[ 0.01595424 -0.05516936  0.88172996]
gt_t:
[-0.04057135  0.11560488  1.02697885]
relative_t:
[0.31794855 0.09627519 0.4105091 ]
pre_t:
[-0.00813901  0.03651872  0.84898686]
gt_t:
[-0.06279779 -0.06689761  0.70487136]
relative_t:
[-0.85244363 -0.03315204  0.79681065]
pre_t:
[ 0.0828982  -0.01474452  0.8731712 ]
gt_t:
[0.06615795 0.06787223 0.94558668]
relative_t:
[-0.66561757 -0.61138706  0.78143209]
pre_t:
[ 0.00263894 -0.0051546   0.9148385 ]
gt_t:
[-0.05273548 -0.07258205  0.85654628]
relative_t:
[-0.22784551 -0.5919647   0.08614906]
pre_t:
[ 0.02762271 -0.05466468  0.85718554]
gt_t:
[-0.21424882 -0.03279807  0.83477002]
relative_t:
[-0.69055957 -0.64333954  0.26019941]
pre_t:
[ 0.04062948 -0.04479127  0.87628454]
gt_t:
[-0.14437869 -0.11147141  0.80331475]
relative_t:
[-0.22257997  0.09164457  0.07678659]
pre_t:
[ 0.06150322 -0.02721429  0.8331722 ]
gt_t:
[-0.10390165 -0.10881608  0.93010026]
relative_t:
[-0.9188009  -0.68562195  0.97793232]
pre_t:
[ 0.01671106 -0.05456759  

2024-01-08 18:26:01.749 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 98 unique items...
2024-01-08 18:26:01.751 | INFO     | __main__:<module>:71 - 
{'AP50': 0.336734693877551,
 'R:ACC15': 0.030612244897959183,
 'R:ACC30': 0.07142857142857142,
 'R:auc@15': 0.017309926636610625,
 'R:auc@30': 0.03472447243063995,
 'R:medianErr': 93.8931881827661,
 't:ACC15': 0.9693877551020408,
 't:ACC30': 1.0,
 't:auc@15': 0.5474290558142895,
 't:auc@30': 0.7730048056275045,
 't:medianErr': 6.602890589263595}
2024-01-08 18:26:01.753 | INFO     | __main__:<module>:7 - LINEMOD: duck_data


pre_t:
[ 0.02267822 -0.0501283   0.9043698 ]
gt_t:
[-0.04497362 -0.04028405  0.68944472]
relative_t:
[ 0.79847654 -0.33115934  0.73735317]
pre_t:
[ 0.04653411 -0.04363111  0.8130476 ]
gt_t:
[-0.02347494 -0.01533428  1.00880694]
relative_t:
[-0.68166879 -0.37614114  1.48277224]
pre_t:
[0.00306378 0.03292847 0.9134579 ]
gt_t:
[ 0.00397474 -0.05854945  0.74016565]
relative_t:
[-0.73573905  0.24648945  0.33178553]
pre_t:
[ 0.00605577 -0.0737006   0.9199895 ]
gt_t:
[ 0.03030385 -0.09241845  0.76570529]
relative_t:
[-0.69063157 -0.72270387  0.81249546]
pre_t:
[-5.2344054e-04 -6.9054827e-02  8.4177405e-01]
gt_t:
[-0.08289263  0.06110197  0.98272014]
relative_t:
[-0.71898253 -0.48728932  0.5025863 ]
pre_t:
[ 0.0363434  -0.04362061  0.87822235]
gt_t:
[ 0.05061933 -0.02354775  1.00985658]
relative_t:
[-0.4840432  -0.3722043   0.69555877]
pre_t:
[-0.01916087 -0.04825211  0.88666505]
gt_t:
[0.15624917 0.10026394 1.00747824]
relative_t:
[ 0.05377761 -0.69715495  0.84077013]
pre_t:
[ 0.00833255 -0.0

2024-01-08 18:26:02.664 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 95 unique items...
2024-01-08 18:26:02.666 | INFO     | __main__:<module>:71 - 
{'AP50': 0.6947368421052632,
 'R:ACC15': 0.010526315789473684,
 'R:ACC30': 0.08421052631578947,
 'R:auc@15': 0.006635941518917299,
 'R:auc@30': 0.026858857699131013,
 'R:medianErr': 87.28089950040567,
 't:ACC15': 1.0,
 't:ACC30': 1.0,
 't:auc@15': 0.588353987842315,
 't:auc@30': 0.7941769939211574,
 't:medianErr': 6.052934945485898}
2024-01-08 18:26:02.666 | INFO     | __main__:<module>:7 - LINEMOD: eggbox_data


pre_t:
[ 0.03682145 -0.08652523  0.92206883]
gt_t:
[-0.02111702 -0.00204939  1.03976321]
relative_t:
[-0.58892412 -0.59149325  1.06338361]
pre_t:
[ 0.06756273 -0.06076379  0.8347901 ]
gt_t:
[-0.01626323  0.00698839  0.76921922]
relative_t:
[-0.45149468 -0.27004118  0.31851604]
pre_t:
[ 0.02178876 -0.06247588  0.8807662 ]
gt_t:
[ 0.13125829 -0.06567648  0.88951862]
relative_t:
[ 0.73610335 -0.49313108  0.54911813]
Acc: 66/95
pre_t:
[-0.01383603 -0.06164607  0.8828099 ]
gt_t:
[-0.02878551 -0.07066323  0.79052609]
relative_t:
[ 0.80339147 -0.53224777  0.78832902]
pre_t:
[ 0.01426928 -0.03655976  0.9137497 ]
gt_t:
[-0.0274256  -0.08404269  0.73670775]
relative_t:
[ 0.63349781 -0.45736742  1.32515494]
pre_t:
[-0.00256595 -0.05109867  0.8806306 ]
gt_t:
[0.10592692 0.02783371 0.90042043]
relative_t:
[-0.28532259  0.41884609  0.2600171 ]
pre_t:
[ 0.03773713 -0.0265302   0.92042035]
gt_t:
[ 0.11504312 -0.02253329  0.91919017]
relative_t:
[-0.52288532 -0.10691918  0.59355666]
pre_t:
[ 0.02165509

2024-01-08 18:26:03.118 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 50 unique items...
2024-01-08 18:26:03.119 | INFO     | __main__:<module>:71 - 
{'AP50': 0.78,
 'R:ACC15': 0.0,
 'R:ACC30': 0.1,
 'R:auc@15': 0.0,
 'R:auc@30': 0.03798285297246569,
 'R:medianErr': 103.93219096356589,
 't:ACC15': 1.0,
 't:ACC30': 1.0,
 't:auc@15': 0.6568111173443626,
 't:auc@30': 0.8284055586721812,
 't:medianErr': 5.201116170406653}
2024-01-08 18:26:03.120 | INFO     | __main__:<module>:7 - LINEMOD: glue_data


gt_t:
[0.12104794 0.00317866 1.04549468]
relative_t:
[ 0.38494846 -0.7175728   0.54339511]
pre_t:
[-6.8339705e-04 -2.1082900e-02  8.2910889e-01]
gt_t:
[-0.10018233 -0.10405175  1.01656425]
relative_t:
[-0.83402914 -0.28644116  0.31067691]
pre_t:
[ 0.00591623 -0.0054712   0.9285828 ]
gt_t:
[-0.00902161  0.00416445  0.95609152]
relative_t:
[ 0.70360383 -0.2206511   0.7587113 ]
pre_t:
[0.01605181 0.00700307 0.9724646 ]
gt_t:
[0.04369401 0.02455745 0.92474437]
relative_t:
[-0.21126459 -0.25688135  0.10388469]
pre_t:
[ 0.07059611 -0.05956812  0.953398  ]
gt_t:
[ 0.089015   -0.01945775  0.83750314]
relative_t:
[ 0.50638998 -0.8959682   1.10989609]
pre_t:
[0.05115834 0.0175444  0.91918266]
gt_t:
[0.01391631 0.0413835  0.92652118]
relative_t:
[ 0.75538466 -0.26613707  0.26724399]
pre_t:
[-0.02012312  0.00254606  0.90796894]
gt_t:
[-0.01411653 -0.09974039  0.8108691 ]
relative_t:
[0.39430915 0.11028567 0.23867656]
Acc: 39/50
pre_t:
[-0.00788415 -0.06791362  0.94768643]
gt_t:
[ 0.06226695 -0.089

2024-01-08 18:26:04.072 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 106 unique items...
2024-01-08 18:26:04.074 | INFO     | __main__:<module>:71 - 
{'AP50': 0.5188679245283019,
 'R:ACC15': 0.04716981132075472,
 'R:ACC30': 0.1320754716981132,
 'R:auc@15': 0.01149461883843111,
 'R:auc@30': 0.053335107221991945,
 'R:medianErr': 80.16301395099784,
 't:ACC15': 0.9905660377358491,
 't:ACC30': 1.0,
 't:auc@15': 0.6313897776048167,
 't:auc@30': 0.8148787174481448,
 't:medianErr': 5.041697047285023}
2024-01-08 18:26:04.075 | INFO     | __main__:<module>:7 - LINEMOD: holepuncher_data


pre_t:
[ 0.04042812 -0.07433823  0.9335271 ]
gt_t:
[ 0.00442109 -0.10208652  1.02096343]
relative_t:
[-0.16591725 -0.22494975  0.28263294]
pre_t:
[ 0.06909398 -0.0315382   0.8488409 ]
gt_t:
[ 0.01067509 -0.092037    1.02827919]
relative_t:
[ 0.60917377 -0.53846779  1.36248175]
pre_t:
[ 0.07135853 -0.06726846  0.79664886]
gt_t:
[-0.012793    0.03123829  0.77354294]
relative_t:
[-0.76990494  0.66128206  0.35012008]
pre_t:
[ 0.06699803 -0.00954084  0.8872697 ]
gt_t:
[-0.17195331 -0.08575299  0.64262944]
relative_t:
[-0.14024324  0.13539299 -0.03682774]
pre_t:
[ 0.05755962 -0.03544077  0.9086237 ]
gt_t:
[-0.01845055 -0.11432882  0.76604503]
relative_t:
[ 0.15804002 -0.70995916  1.2647361 ]
pre_t:
[ 0.01175854 -0.03954998  0.84696835]
gt_t:
[ 0.01563698 -0.0381986   1.04976046]
relative_t:
[ 0.85469196 -0.37214459  1.22661177]
pre_t:
[ 0.04502553 -0.011582    0.768292  ]
gt_t:
[ 0.04192112 -0.00097722  0.83460295]
relative_t:
[-0.80081873 -0.48839551  0.56226279]
pre_t:
[ 0.03131973 -0.0204

2024-01-08 18:26:04.982 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 100 unique items...
2024-01-08 18:26:04.985 | INFO     | __main__:<module>:71 - 
{'AP50': 0.6831683168316832,
 'R:ACC15': 0.009900990099009901,
 'R:ACC30': 0.0594059405940594,
 'R:auc@15': 0.006028517686461005,
 'R:auc@30': 0.022328009888535928,
 'R:medianErr': 83.45973578246598,
 't:ACC15': 1.0,
 't:ACC30': 1.0,
 't:auc@15': 0.5953643583131917,
 't:auc@30': 0.7976821791565958,
 't:medianErr': 5.880983315977145}
2024-01-08 18:26:04.986 | INFO     | __main__:<module>:7 - LINEMOD: iron_data


pre_t:
[ 0.02980369 -0.0049343   0.91818696]
gt_t:
[ 0.03751476 -0.05181159  0.80459243]
relative_t:
[ 0.69592139 -0.03244462  0.37088087]
Acc: 69/101
pre_t:
[0.04459916 0.01225819 0.93583906]
gt_t:
[-0.11674778 -0.05579774  0.89908743]
relative_t:
[-0.01921845  0.08908519  0.23920485]
pre_t:
[ 0.04582434 -0.05375985  1.007879  ]
gt_t:
[-0.09377679  0.00658303  0.80910999]
relative_t:
[-0.20375201 -0.90843825  1.26970496]
pre_t:
[-0.01529925 -0.01649324  0.8624283 ]
gt_t:
[ 0.00797109 -0.11678863  1.03309309]
relative_t:
[-0.59030428 -0.27383195  0.51363037]
pre_t:
[0.0103718  0.02320328 0.91867197]
gt_t:
[ 0.09551607 -0.08279914  0.79122382]
relative_t:
[ 0.63705433 -0.97170204  0.8601572 ]
pre_t:
[ 0.03729642 -0.02971567  0.8790393 ]
gt_t:
[ 0.00936767 -0.0272154   0.97080827]
relative_t:
[ 0.61664054 -0.35927497  0.97792019]
pre_t:
[ 0.06839418 -0.0353109   0.8187511 ]
gt_t:
[-0.07789758  0.02958314  0.90665174]
relative_t:
[-0.80843901  0.09270533  0.23889565]
pre_t:
[0.02442793 0.

2024-01-08 18:26:05.416 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 45 unique items...
2024-01-08 18:26:05.417 | INFO     | __main__:<module>:71 - 
{'AP50': 0.4444444444444444,
 'R:ACC15': 0.06666666666666667,
 'R:ACC30': 0.17777777777777778,
 'R:auc@15': 0.029744836999401173,
 'R:auc@30': 0.08808044567277286,
 'R:medianErr': 76.90250976155814,
 't:ACC15': 1.0,
 't:ACC30': 1.0,
 't:auc@15': 0.5728807121111196,
 't:auc@30': 0.7864403560555597,
 't:medianErr': 5.789492286276172}
2024-01-08 18:26:05.418 | INFO     | __main__:<module>:7 - LINEMOD: lamp_data


pre_t:
[ 0.03289165 -0.0379747   0.83173573]
gt_t:
[ 0.00220194 -0.17555639  0.90378082]
relative_t:
[-0.75828465 -0.55238634  0.58230131]
Acc: 20/45
pre_t:
[-0.04158088 -0.05433287  0.85983944]
gt_t:
[ 0.06293269 -0.11990828  0.86672729]
relative_t:
[ 1.06440869 -0.16107166  0.60828228]
pre_t:
[ 0.03870953 -0.03603489  0.7741514 ]
gt_t:
[ 0.06293269 -0.11990828  0.86672729]
relative_t:
[-0.11704568 -0.90327229  0.61343271]
pre_t:
[ 0.03345352 -0.06555639  0.8890752 ]
gt_t:
[-0.00646472 -0.03550887  0.75419533]
relative_t:
[-0.37677187 -0.57566752  0.36337593]
pre_t:
[ 0.04973909 -0.04570401  0.8332126 ]
gt_t:
[ 0.05628709 -0.00485256  0.87217116]
relative_t:
[0.71625324 0.12539254 0.20998601]
pre_t:
[ 0.0501378  -0.05628039  0.81206495]
gt_t:
[ 0.02407844 -0.12187865  0.98431665]
relative_t:
[-0.7935992  -0.67676922  1.3407101 ]
pre_t:
[ 0.02388703 -0.02365085  0.9360677 ]
gt_t:
[-0.05944727 -0.09424346  0.6877327 ]
relative_t:
[-0.84062992 -0.46884636  0.84156825]
pre_t:
[ 0.04405846

2024-01-08 18:26:06.209 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 83 unique items...
2024-01-08 18:26:06.211 | INFO     | __main__:<module>:71 - 
{'AP50': 0.44047619047619047,
 'R:ACC15': 0.011904761904761904,
 'R:ACC30': 0.16666666666666666,
 'R:auc@15': 0.008690858457737616,
 'R:auc@30': 0.052937082191625504,
 'R:medianErr': 76.65179379587128,
 't:ACC15': 0.9880952380952381,
 't:ACC30': 1.0,
 't:auc@15': 0.5699096240533815,
 't:auc@30': 0.7850559530878033,
 't:medianErr': 5.995505908623905}
2024-01-08 18:26:06.212 | INFO     | __main__:<module>:7 - LINEMOD: phone_data


pre_t:
[-0.00284237 -0.03827496  0.87389433]
gt_t:
[-0.03543714 -0.06364609  0.73405546]
relative_t:
[ 0.68720102 -0.32636437  0.01450443]
pre_t:
[ 0.05070857 -0.07924861  0.8300471 ]
gt_t:
[-0.04868753 -0.16056868  0.85253555]
relative_t:
[-0.01677914 -0.51912512  0.33078806]
pre_t:
[ 0.0440461  -0.02853968  0.94791716]
gt_t:
[-0.14722988 -0.05794331  1.03325641]
relative_t:
[0.52310959 0.08620576 0.27397629]
pre_t:
[-0.02097519 -0.06944832  0.8528161 ]
gt_t:
[0.09840423 0.03927929 0.9829582 ]
relative_t:
[ 1.02222323 -0.28278595  0.69198357]
pre_t:
[ 0.06213376 -0.01742427  0.9052592 ]
gt_t:
[ 0.11523277 -0.05167022  0.6415264 ]
relative_t:
[-0.04647344 -0.57181059 -0.20868021]
pre_t:
[ 0.02143456 -0.0231365   0.804458  ]
gt_t:
[-0.02766579  0.05353888  1.03075457]
relative_t:
[-0.2697094  -0.53968676  1.06359864]
pre_t:
[ 0.03427361 -0.04516823  0.78870684]
gt_t:
[ 0.03011    -0.10762621  0.67198336]
relative_t:
[ 0.0603273  -0.74122353  0.99892786]
pre_t:
[ 0.04917078 -0.04324688  

2024-01-08 18:26:07.042 | INFO     | src.utils.metrics:aggregate_metrics:192 - Aggregating metrics over 89 unique items...
2024-01-08 18:26:07.044 | INFO     | __main__:<module>:71 - 
{'AP50': 0.33707865168539325,
 'R:ACC15': 0.02247191011235955,
 'R:ACC30': 0.06741573033707865,
 'R:auc@15': 0.009722257995613765,
 'R:auc@30': 0.0270744558230742,
 'R:medianErr': 63.244846728456174,
 't:ACC15': 1.0,
 't:ACC30': 1.0,
 't:auc@15': 0.5820350361176766,
 't:auc@30': 0.7910175180588382,
 't:medianErr': 6.001364306984559}


pre_t:
[ 0.07578838 -0.04912034  0.8705179 ]
gt_t:
[ 0.02073299 -0.01880141  1.00287044]
relative_t:
[-0.63895971 -0.0638043   0.74656474]
pre_t:
[ 0.07016094 -0.01175529  0.8484143 ]
gt_t:
[ 0.30521265 -0.06345942  0.99623257]
relative_t:
[ 0.05309722 -0.62940464  0.39182842]
pre_t:
[0.00817125 0.02008631 0.905445  ]
gt_t:
[-0.0064622  -0.10310427  1.03794229]
relative_t:
[-0.45155877 -0.04507274  0.13954002]
pre_t:
[-0.02791081 -0.07842454  0.82456076]
gt_t:
[-0.0073779  -0.08888417  0.99985284]
relative_t:
[0.93919507 0.11583653 0.53212988]
pre_t:
[ 0.04852004 -0.06476907  0.84239864]
gt_t:
[0.02990725 0.04220477 0.85955149]
relative_t:
[ 0.4216581  -0.40966789  0.35015944]
pre_t:
[ 0.07879925 -0.05749088  0.76832175]
gt_t:
[-0.12342578  0.02391978  1.03365493]
relative_t:
[-0.04707529 -0.87845502  1.53975161]
pre_t:
[-0.00546962 -0.03104579  0.8449845 ]
gt_t:
[-0.07509425 -0.01384886  1.003124  ]
relative_t:
[-0.38694965 -0.57823912  0.72458268]
pre_t:
[ 0.02289686 -0.09667017  0.8

In [10]:
from tabulate import tabulate
headers = ["Category"] + list(val_metrics_4tb.keys())
all_data = np.array(res_table)[:, 1:].astype(np.float32)
res_table.append(["Avg"] + all_data.mean(0).tolist())
print(tabulate(res_table, \
    headers=headers, tablefmt='fancy_grid'))

╒═════════════╤════════════╤════════════╤════════════╤═══════════╤═══════════════╤════════════╤════════════╤═══════════╤═══════════╤═══════════════╤══════════╕
│ Category    │   R:auc@15 │   R:auc@30 │    R:ACC15 │   R:ACC30 │   R:medianErr │   t:auc@15 │   t:auc@30 │   t:ACC15 │   t:ACC30 │   t:medianErr │     AP50 │
╞═════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════════╪══════════╡
│ ape         │ 0.00780565 │  0.0435189 │ 0.00980392 │ 0.156863  │       66.1976 │   0.43515  │   0.713773 │  0.931373 │         1 │       8.66588 │ 0.637255 │
├─────────────┼────────────┼────────────┼────────────┼───────────┼───────────────┼────────────┼────────────┼───────────┼───────────┼───────────────┼──────────┤
│ benchvise   │ 0.00773137 │  0.0419144 │ 0.0140845  │ 0.112676  │       90.4596 │   0.574702 │   0.787351 │  1        │         1 │       6.1467  │ 0.338028 │
├─────────────┼────────────┼────────────